### ISSUE TITLE
Add a 'medium' contour to a 2D mesh

### ISSUE THREAD

**Issue by jeanmichelscherer** [DorianDepriester/MTEX2Gmsh#9] opened 2021-03-24 14:36 UTC
Hi,

The 'medium' option works perfectly in 3D.
I wondered if it also available in 2D, i.e. without extrusion.
I tried by giving a list of only two dimensions, or by setting the last dimension to 0, but without success.

Thanks

Jean-Michel

**Comment by DorianDepriester** [comment] 2021-03-24 15:05
Hi Jean-Michel,
Currently, this feature has been designed for 3D only. I can try to have a look on 2D. I will notice you once it's done.
Regards

**Comment by DorianDepriester** [comment] 2021-03-26 11:37
This issue is now fixed. You should be able to add a surrounding medium (referred to as 'Medium' in the mesh) in 2D meshes. The dimensions for the surrounding medium are of course of length 2 (ex: ``[dx dy]``) in this case.

**Comment by jeanmichelscherer** [comment] 2021-03-26 11:46
Great! It works as expected.

**Comment by kun-Jiang** [comment] 2023-03-24 13:38
Sorry to bother you again, I tend to get a 2D mesh by the following command. I have tested mtex version of 5.3.1 and 5.8.0 but there didn't appear medium surround the ROI. And there were still four nodes existing in the margin of the medium.
`mesh(G,'titanium-medium.msh','ElementType','Quad','ElementSize',20,'medium',[1000 1000]);`
![titanium-medium](https://user-images.githubusercontent.com/53817143/227536021-9fa9a75e-3102-4c06-a11f-785ea18cc7aa.jpg)

**Comment by DorianDepriester** [comment] 2023-03-27 07:42
Hello @kun-Jiang,
Thank you for reporting this issue, and sorry for the inconvenience. The issue is hopefully fixed now. Download the latest version (not from releases) and it should work.

**Closed by DorianDepriester** 2023-03-27 07:42 UTC

**Comment by kun-Jiang** [comment] 2023-03-28 02:37
Thanks, Dorian, it works!
