### ISSUE TITLE
Physical Surface when meshing in 2D

### ISSUE THREAD

**Issue by jeanmichelscherer** [DorianDepriester/MTEX2Gmsh#8] opened 2021-03-24 14:23 UTC
Hi Dorian,

Very nice toolbox! Thanks for sharing.

When using savegeo() to create a GMSH geometry file like as follows:

   savegeo(G,strcat(output,'.geo'),'ElementSize',elt_size,'gradient',gradient,'ElementType','Tri');

The .geo file contains lines to create Physical Volumes (just below // Sets), although the given options will result in a 2D mesh.
Would it make sense to replace "Physical Volume" by "Physical Surface" when 2D mesh options are passed as arguments to the savegeo function ?

Regards

Jean-Michel

**Comment by DorianDepriester** [comment] 2021-03-24 15:06
You are completely right. I will update it as soon as possible.

**Comment by DorianDepriester** [comment] 2021-03-26 08:32
Hello Jean-Michel,
  The issue is now fixed. 
I have also noticed that the geometry was not meshed when 2D. I guess that's why you use ``savegeo`` instead of ``mesh``.

**Closed by DorianDepriester** 2021-03-26 08:32 UTC

**Comment by jeanmichelscherer** [comment] 2021-03-26 10:03
Hello Dorian,
I did not notice the second issue you mention although I have been using both `savegeo` and `mesh` functions.
Anyways, thanks for the fix, it works perfectly.
